let countriesToVisit: string[] = ["China", "Iran", "Australia", "France"];
console.log("Original Order:", countriesToVisit);
console.log("Alphabetical order:", [...countriesToVisit].sort());
console.log("Still in original order:", countriesToVisit);
console.log("reverse order:", [...countriesToVisit].reverse());
console.log("Still in original order:", countriesToVisit);
console.log("Original array reversed:", countriesToVisit.reverse());
console.log("back to Original Order:",countriesToVisit.reverse());
console.log("Sorted in Alphabetical Order:", countriesToVisit.sort());
console.log("Original array reversed again:", countriesToVisit.reverse());